config/routes.rb
Seatyourself::Application.routes.draw do
  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"
  root "home#index"
  
  resources :owners, except: :index

  resources :customers, except: :index do
  	resources :reservations, only: :index
  end

  resources :sessions, only: [:new, :create, :destroy]

  resources :restaurants do
  	resources :reservations, except: :index
  end

end

app/models/customer.rb
class Customer < ActiveRecord::Base
	has_secure_password
	
	validates_uniqueness_of :email

	mount_uploader :image, ImageUploader

	has_many :reservations

	has_many :restaurants, through: :reservations


end

app/models/owner.rb
class Owner < ActiveRecord::Base

	has_secure_password

	validates_uniqueness_of :email

	has_many :restaurants

	mount_uploader :image, ImageUploader
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base

	belongs_to :customer
	belongs_to :restaurant

	validate :less_than_max_occupancy


	def less_than_max_occupancy
	  other_people = Reservation.where(:restaurant_id => self.restaurant_id, :time_slot => self.time_slot.day, :time_slot => self.time_slot.hour).sum(:groupsize)

	  if other_people + self.groupsize > 10
	     errors.add(:base, "Cannot accommodate group size for specified time")
	  end
	end

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	validates :name, :address, :phone_number,  presence: true

	belongs_to :owner

	has_many :customers, through: :reservations

	has_many :reservations

	mount_uploader :image, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception


  
  def current_user
    if session[:customer_id] == nil
      @current_user ||= Owner.find(session[:owner_id]) if session[:owner_id]
    else
      @current_user ||= Customer.find(session[:customer_id]) if session[:customer_id]
  	end
  end

  helper_method :current_user

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def new
  	@customer = Customer.new
  end

  def edit
  	@customer = Customer.find(params[:id])
  end

  def show
  	@customer = Customer.find(params[:id])
  end

  def create
  	@customer = Customer.new(customer_params)
  	if @customer.save
  		session[:customer_id] = @customer.id
  		redirect_to root_path, alert: "Account created"
  	else
  		render :new
  	end
  end

  def update
  	@customer = Customer.find(params[:id])
  	if @customer.update_attributes(customer_params)
  		redirect_to customer_path(@customer)
  	else
  		render :edit
  	end
  end

  def destroy
  	@customer = Customer.find(params[:id])
  	if @customer.destroy
      reset_session
  		redirect_to root_path
  	else
  		render :edit
  	end
  end

  private

  	def customer_params
  		params.require(:customer).permit(:email, :name, :password, :password_confirmation)
  	end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	@restaurants = Restaurant.all
  end
end

app/controllers/owners_controller.rb
class OwnersController < ApplicationController

	before_action :find_owner, only: [:show, :edit, :update, :destroy]

	def new 
		@owner = Owner.new
	end

	def create
		@owner = Owner.new(owner_params)
		if @owner.save
			session[:owner_id] = @owner.id
			redirect_to owner_path(current_user), alert: "Signed up"
		else
			render :new
		end
	end

	def show
	end

	def edit
	end

	def update
		if @owner.update_attributes(owner_params)
			redirect_to owner_path(current_user)
		else
			render :edit
		end
	end

	def destroy
		if @owner == current_user
			@owner.destroy
			reset_session
			redirect_to root_path, alert: "Account has been deleted"
		else 
			render :edit
		end
	end

	private
	
	def owner_params
		params.require(:owner).permit(:name, :email, :password, :password_confirmation)
	end

	def find_owner
		@owner = Owner.find(params[:id])
	end

end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_action :find_reservation, only: [:edit, :show, :update, :destroy]

	def new
    #@customer = Customer.find(params[:customer_id])
     @restaurant = Restaurant.find(params[:restaurant_id])
     @reservation = @restaurant.reservations.build
 	end
  
  	def index
    @reservations = Reservation.where(customer_id: current_user.id)
  	end
  
  	def create
    #@customer = Customer.find(params[:customer_id])
    	@restaurant = Restaurant.find(params[:restaurant_id])
    	@reservation = @restaurant.reservations.build(reservation_params) #&& @customer.reservations.build(params[:reservation])
    	@reservation.customer_id = current_user.id
        if @reservation.save
      		redirect_to root_path
        else
      		render :new
        end
  	end

  	def show
  	end

  	def edit
      @restaurant = Restaurant.find(params[:restaurant_id])
      #@reservation = Reservation.find(params[:id])
      
  	end

  	def update
    	if @reservation.update_attributes(reservation_params)
     		 redirect_to customer_path(current_user)
    	else
      		render :edit
    	end
  	end

  	def destroy
      @restaurant = Restaurant.find(params[:restaurant_id])
   		@reservation.destroy
    	redirect_to root_path, notice: "reservation deleted"
  	end

  private

    def reservation_params
      params.require(:reservation).permit(:time_slot, :restaurant_id, :customer_id, :groupsize)
    end

  	def restaurant_params
		  params.require(:restaurant).permit(:name, :address, :image, :phone_number, :website_url, :owner_id, :capacity)
    end

    def find_reservation
      @reservation = Reservation.find(params[:id])
    end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurant = Restaurant.find(params[:id])
	end

	def edit
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.owner_id == current_user.id
			render :edit
		end
	end

	def new
		@restaurant = Restaurant.new
	end

	def create
		@restaurant = Restaurant.new(restaurant_params)
		@restaurant.owner_id = current_user.id
		if @restaurant.save
			redirect_to restaurant_path(@restaurant), notice: "#{@restaurant.name} has been created"
		else
			render :new
		end
	end

	def update
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.owner_id == current_user.id
			@restaurant.update_attributes(restaurant_params)
			redirect_to restaurant_path(@restaurant), notice: "Page has been updated"
		else
			render :edit
		end
	end

	def destroy
		@restaurant = Restaurant.find(params[:id])
		if @restaurant.destroy#@restaurant.owner_id == current_user.id
			redirect_to owner_path(current_user), notice: "Restaurant has been deleted"
		else
			redirect_to restaurant_path(@restaurant)
		end
	end

	private

	def restaurant_params
		params.require(:restaurant).permit(:name, :address, :image, :phone_number, :website_url, :owner_id, :capacity)
	end

	def reservation_params
			params.require(:reservation).permit(:time_slot, :groupsize, :restaurant_id, :customer_id)
	end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    @owner = Owner.where(email: params[:email]).first
    if @owner
      if @owner.authenticate(params[:password])
        session[:owner_id] = @owner.id
        redirect_to root_path, notice: "Welcome, #{@owner.name}"
      else
      flash.now[:alert] = "Invalid email or password"
      render :new
      end
    else 
      @customer = Customer.where(email: params[:email]).first
      if @customer
        if @customer.authenticate(params[:password])
          session[:customer_id] = @customer.id
          redirect_to root_path, notice: "Welcome, #{@customer.name}"
        else 
          flash.now[:alert] = "Invalid email or password"
          render :new
        end
      end
    end
  end

  def destroy
    session[:owner_id] = nil
    session[:customer_id] = nil
    redirect_to root_path, notice: "Logged out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/owners_helper.rb
module OwnersHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/customers/_aside.html.erb
 <h5>Profile Options</h5>
      
<li><%= link_to "My Reservations", customer_reservations_path(customer_id: current_user.id) %></li>
<li><%= link_to "Edit Profile", edit_customer_path(current_user) %></li>
     
 

app/views/customers/_form.html.erb
<div class="form">
	<%= form_for @customer do |f| %>

	<div class="field">
		<%= f.label :name %><br />
		<%= f.text_field :name %>
	</div>

	<div class="field">
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</div>

	<div class="field">
		<%= f.label :image %><br />
		<%= f.file_field :image %>
	</div>

	<div class="field">
		<%= f.label :password %><br />
		<%= f.password_field :password %>
	</div>

	<div class="field">
		<%= f.label :password_confirmation %><br />
		<%= f.password_field :password_confirmation %>
	</div>

	<div class="action">
	<%= f.submit %>
	</div>
	<%end%>
</div>

app/views/customers/edit.html.erb
<%= render 'form' %>

<%= link_to "Delete Account", session_path(current_user), method: :delete %>

app/views/customers/new.html.erb
<%= render 'form' %>

app/views/customers/show.html.erb
<%= render 'aside'%>

<h1> <%= @customer.name %></h1>

<div class="customer">
	<p><%= @customer.email %></p> 
</div>

app/views/home/index.html.erb
<%= link_to "Restaurants", restaurants_path %> |

<% if current_user == nil %>
<%= link_to "Log in", new_session_path %> | <%= link_to "Join as Customer", new_customer_path %> | <%= link_to "Join as Business Owner", new_owner_path %>
<% elsif session[:owner_id] == current_user.id %>  
<%= link_to "My Profile", owner_path(current_user) %> |
<%= link_to "Log out", session_path(current_user), method: :delete %> 
<% elsif session[:customer_id] == current_user.id %> 
<%= link_to "My Profile", customer_path(current_user) %> |
<%= link_to "Log out", session_path(current_user), method: :delete %>
<%end%>

app/views/layouts/_header.html.erb
        <h1>
          <%= link_to "Seat Yourself", root_path %>
        </h1>
     
 

app/views/layouts/application.html.erb
<!DOCTYPE html>

  <head>
  	<meta charset="utf-8" />

  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "Seat Yourself" %></title>


    <%= csrf_meta_tags %>
  </head>

  <body>
  <%= render 'layouts/header' %>
    <%= yield %>

    
    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/owners/_form.html.erb
<%= form_for @owner do |f| %>

<div class="field">
<%= f.label :name %><br />
<%= f.text_field :name %>
</div>

<div class="field">
<%= f.label :email %><br />
<%= f.text_field :email %>
</div>

<div class="field">
<%= f.label :password %><br />
<%= f.password_field :password %>
</div>

<div class="field">
<%= f.label :password_confirmation %><br />
<%= f.password_field :password_confirmation %>
</div>

<div class="action">
<%= f.submit %>
</div>

<%end%>

app/views/owners/edit.html.erb
<%= render 'form' %>

<%= link_to "Cancel", owner_path(@owner) %>
<%= link_to "Delete Account", owner_path(@owner), method: :delete, data: {confirm: "Are you sure?"} %>

app/views/owners/new.html.erb
<h1>Create new owner account</h1>

<%= render 'form' %>

<%= link_to "Cancel", root_path %>

app/views/owners/show.html.erb
<h1>Owner's Profile</h1>

<div class="owner">
	<h2><%= @owner.name %></h2>
	<p><%= @owner.email %></p> 
</div>

<%= link_to "Edit Profile", edit_owner_path %> | 
<%= link_to "Home", root_path %> | 
<%= link_to "Create New Restaurant", new_restaurant_path %> | 
<%= link_to "My Restaurants", restaurants_path %>

app/views/reservations/_form.html.erb
<div class="large-8 columns">
	<%= form_for [@restaurant, @reservation] do |f| %>
		<div class="field">
				<% if @reservation.errors.any? %>
	    			<div id="error_explanation">
	      				<h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

			    		<ul>
			      			<% @reservation.errors.full_messages.each do |msg| %>
			        		<li><%= msg %></li>
			    			<% end %>
	      				</ul>
	    			</div>
	 			<% end %>
	 	</div>

		<div class="field">
			<%= f.label :select_date %>
			<%= f.datetime_select(:time_slot, start_year: Time.now.year, end_year: Time.now.year, ampm: true, prompt: {month: 'Month', day: 'Day', hour: 'Hour'}) %>
		</div>

		<div class="field">
			<%= f.label :groupsize %>
			<%= f.select :groupsize, 1..10 %>
		</div>

		<div>
			<%= f.submit %>
		</div>

	<%end%>

</div>

app/views/reservations/edit.html.erb
<div class="row">
<%= render 'reservations/form' %>
</div>

<div class="row">
	<div class="large-8 columns">
		<%= link_to "Delete Reservation", restaurant_reservation_path(restaurant_id: @reservation.restaurant_id, id: @reservation.id), method: :delete, data: {confirm: "Are You Sure?"} %> | <%= link_to "Cancel", customer_reservations_path(customer_id: current_user.id) %>
	</div>
</div>

app/views/reservations/index.html.erb
<% @reservations.each do |reservation| %>
<div>
	<h5><%= reservation.restaurant[:name] %></h5>
	<div>
		<%= reservation.time_slot.strftime("%b %e, %l:%M %p") %>
	</div>

	<div>
		Group Size: <%= reservation.groupsize %>
	</div>
<%= link_to "Edit Reservation", edit_restaurant_reservation_path(restaurant_id: reservation.restaurant_id, id: reservation.id)%>
</div>

<%end%>

app/views/reservations/new.html.erb
<%= render 'reservations/form' %>

app/views/reservations/show.html.erb
<div>
<p> Reservation information for <%= @restaurant.name %> </p>
	<div>
		<%= @reservation.time_slot %>
		<%= @reservation.groupsize %>
	</div>
</div>

app/views/restaurants/_aside.html.erb
<aside class="large-4 columns">
 
      <h5>Profile Options</h5>
      <ul class="side-nav">
        <li><%= link_to "My Reservations", customer_reservations_path(customer_id: current_user.id) %></li>
        <li><%= link_to "Edit Profile", edit_customer_path(current_user) %></li>
      </ul>
 
</aside>

app/views/restaurants/_form.html.erb
<%= form_for @restaurant do |f| %>

<% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
 <% end %>

<%= f.label :name %><br>
<%= f.text_field :name %><br>

<%= f.label :capacity %><br>
<%= f.number_field :capacity %><br>

<%= f.label :address %><br>
<%= f.text_field :address %><br>

<%= f.label :phone_number %><br>
<%= f.text_field :phone_number %><br>


<!-- 
<%= f.label :website_url %><br>
<%= f.text_field :website_url %><br> -->
<!-- 
<%= f.label :image %><br />
<%= f.file_field :image %> -->

<%= f.submit %>

<%end%>

app/views/restaurants/_slider.html.erb
<div class="row">
    <div class="large-12 columns">
    	<div id="featured">
    		<% @restaurants.each do |restaurant| %>
    		<%= image_tag("slider/#{restaurant.image}")%>
    		<%end%>
    	</div>
    <hr />
    </div>
</div>

app/views/restaurants/edit.html.erb
<%= render 'form' %>

<%= link_to "Cancel", owner_path(current_user) %>

app/views/restaurants/index.html.erb
<% @restaurants.each do |restaurant| %>

<h5><%= link_to restaurant.name, restaurant %></h5>
    
<%end%>

app/views/restaurants/new.html.erb
<%= render 'form' %>

<%= link_to "Cancel", owner_path(current_user) %>

app/views/restaurants/show.html.erb
<!-- 
<p> <%= image_tag @restaurant.image %></p> -->


<h4><%= @restaurant.name %> Information</h4>
<p>Address: <%= @restaurant.address %></p>
<p>Telephone: <%= @restaurant.phone_number %></p>
<p>Capacity: <%= @restaurant.capacity %></p>


<h4>Options</h4>

<% if current_user == nil %>
<%= link_to "Log in", new_session_path %> | <%= link_to "Join as Customer", new_customer_path %> | <%= link_to "Join as Business Owner", new_owner_path %>

<% elsif session[:owner_id] == current_user.id %>
<li><a href="#"><%= link_to "Home", root_path %></a></li>
<li><a href="#"><%= link_to "My Profile", owner_path(current_user) %></a></li>
<li><a href="#"><%= link_to "Edit Restaurant", edit_restaurant_path(@restaurant) %></a></li>

<% elsif session[:customer_id] == current_user.id %>
<li><a href="#"><%= link_to "Home", root_path %></a></li>
<li><a href="#"><%= link_to "My Profile", customer_path(current_user) %></a></li>
<li><a href="#"><%= link_to "Make Reservation", new_restaurant_reservation_path(@restaurant)%></a></li>

<%else%>
<li><a href="#"><%= link_to "Home", root_path %></a></li>
<%end%>
        